# Generated by Django 2.0.2 on 2018-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='leaving_date',
            field=models.DateTimeField(null=True),
        ),
    ]
